version: "2"
services:
  sails:
    build: .
    depends_on:
      - mongo
    command: forever -wc 'node --harmony' app.js
    ports:
      - "1337:1337"
    links:
      - mongo
    tty: true
    volumes:
      - .:/server
      - /server/node_modules
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo:2.6.6
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
